### ISSUE TITLE
ffxiv mode failing to find the game's executable

### ISSUE THREAD

**Issue by Poldovico** [HereInPlainSight/gshade_installer#11]
I've cloned the repo from github and tried to run the ffxiv autodetect, but I get this output:

```
$ ./gshade_installer.sh ffxiv

Lutris install found!find: ‘/media/poldovico/Games/Lutris/final-fantasy-xiv-online\n''/drive_c’: File or directory does not exist

	Prefix location: /media/poldovico/Games/Lutris/final-fantasy-xiv-online
''
	Game location: 
Install? y
Installing...  ./gshade_installer.sh: riga 476: pushd: $'/media/poldovico/Games/Lutris/final-fantasy-xiv-online\n\'\'': File or directory does not exist
```
There seems to be a random newline getting in there from somewhere, but I can't figure out where from.

**Comment by Poldovico** [comment]
I worked around it by installing as a custom game, so no worries there, but it seems like I might have found either a bug or a weird corner case, so I figured you might want to know about it.

**Comment by HereInPlainSight** [comment]
Updated awk statements to be a bit more discriminating in what they accept as a prefix and version.

Seems to work with `prefix_command` in the lutris yml file as we discussed in Discord.  Thanks again for the report!
