### ISSUE TITLE
What is the correct way to update GShade and Presets in an already-installed game?

### ISSUE THREAD

**Issue by Arcitec** [HereInPlainSight/gshade_installer#21]
Hi, thank you so much for this script. I'm using it with XLCore and it's working flawlessly! :) GitHub Star +1!

I wonder what the proper way is to update the GShade and the presets via the menu?

```
./gshade_installer.sh 
Welcome to GShade!  Please select an option:
	1) Check for an update to GShade
	2) Install to a custom game
	P) Update presets
	F) Attempt auto-install for FFXIV
	B) Create a backup of existing GShade game installations
	S) Show games GShade is installed to
	L) Change GShade's language
	R) Remove game from installed games list
	D) Delete GShade from game and remove from list
	0) Redownload compilers
	Q) Quit
```

I am currently doing these in order:

```
1) Check for an update to GShade
P) Update presets
F) Attempt auto-install for FFXIV
```

It's probably overkill, but the menu isn't clear about which ones are supposed to be used for updates. For all I know, maybe `F` already does a "update GShade and Presets and update the game folder". Heck, maybe `Check for update` and `Update presets` also already auto-install, so F is unnecessary.

Without reading the script in depth, I can only speculate what the proper update method is...

Perhaps the text labels in the menu can be rewritten a bit to clarify the update-process without users having to refer to external sources such as this GitHub ticket. :D

Anyway, thanks again for this beautiful installer. I love having it natively handle without needing to use Wine to run the GShade.exe. <3

**Comment by HereInPlainSight** [comment]
Hey, sorry for the confusion here!  So effectively, option `1` will update everything -- GShade itself _and_ presets, but only if there's a new GShade version available.  GShade itself is handled by a symlink, so all installs are automatically updated -- the presets are manually copied over.  (This menu item is equivalent to `./gshade_installer.sh update`.)

`P` will update all game's presets from the latest available online.  Note that option `1` and `P` will both create backups of your presets, just to make sure you don't lose anything.  (This menu item is equivalent to `./gshade_installer.sh update presets`.)

`F` in this case is unnecessary after the initial install -- the script remembers where things are, so as long as nothing's changed from your initial install, everything should update per the above options.

Would a section on updating to the main github page have resolved this issue in advance, do you feel?  I worry about making the menu look too clunky with too much explanation, is all.

**Comment by Arcitec** [comment]
@HereInPlainSight 

Ahh thank you for the explanation! Then I'll do `1` to check for GShade updates and if that didn't give any result I'll add `P` to at least get new presets.

A section about "How to update" on the main README.md would have helped a lot, yeah! That's a great idea. :) I was looking for info in the whole readme.

As for the menu items, they're probably possible to reword a little bit without being clunky...

```
./gshade_installer.sh 
Welcome to GShade!  Please select an option:
	1) Update GShade and presets
	2) Install to a custom game
	P) Update only presets
	F) Attempt auto-install for FFXIV (not necessary for updates)
	B) Create a backup of existing GShade game installations
	S) Show games GShade is installed to
	L) Change GShade's language
	R) Remove game from installed games list
	D) Delete GShade from game and remove from list
	0) Redownload compilers
	Q) Quit
```

I changed the text of 1, P and F. And have a proposal for modifying the `1` function:

- If no new GShade is found, trigger a `P` internally. This means it's just 1 click to update GShade and presets. Does that sound worth it? I don't think there's any reason to inhibit preset updates if a person asks for a GShade update. So if there was no GShade news, at least getting new Presets sounds good. :)

**Comment by HereInPlainSight** [comment]
Hey!  I'm so sorry for the delay on this, life got somewhat excessively busy for the past month.

I updated `1` and `P`'s wording per your suggestions, I hesitated on `F` just because I felt like if I put it there, I should put it at `2`, and started feeling like it was a bit of a slippery slope, but I also added a small section on Updating to the README.

Do these options all seem like they would, for the most part, have avoided the confusion in the first place?

**Comment by HereInPlainSight** [comment]
Closing, but feel free to re-open / comment if you feel the issue hasn't been fully addressed!

**Comment by Arcitec** [comment]
@HereInPlainSight Hey again, thank you so much for everything. The new menu labels and the readme's "updating" section definitely make things much clearer. I appreciate you so much for creating this awesome tool. :) Have a happy new year! :)
