### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by wjpower2003** [HereInPlainSight/gshade_installer#9]
I'm something of a newb with Gshade and Linux so it will probably be the case that I'm just being stupid but I'm trying to install Gshade on my Pop!_OS system for the game Kingdom Come Deliverance but when I try option 2 (install to a custom game) I input the location of the WINEPREFIX $HOME/.local/share/Steam/steamapps/compatdata/379430/pfx but a message is returned saying that the directory does not exist. 

I have a reshade installation in my Kingdom Come folder which I could fall back on but it is currently being overridden by Gshade in-game but there are not settings/presets available because they haven't actually been installed.

I can't physically delete Gshade from my computer because I initially placed the installer in it's current location using root # rather than $

Could anybody give me any advice?

Thanks in advance.

**Comment by HereInPlainSight** [comment]
Hey!  I'm a little uncertain of some of your setup, but the first thing is that when inputting the directory via the menu, be explicit.  The command line version of input will interpret `$HOME`, but once inside the script, it will not.  :)

As for GShade overwriting ReShade -- I'm confused.  Is the installer owned by root, or did you successfully install GShade to the game, but you did so as root?  The earlier part of your question indicates GShade wasn't successfully installed, so GShade shouldn't be showing up in your game at all.

If I'm misunderstanding, and you _did_ successfully install GShade to the game, but did so as root, you should be able to remove the install by using GShade with `sudo ./gshade_installer.sh`, although this should only be used for cleaning up.  The installer should never be run as root.

**Comment by wjpower2003** [comment]
> Hey! I'm a little uncertain of some of your setup, but the first thing is that when inputting the directory via the menu, be explicit. The command line version of input will interpret `$HOME`, but once inside the script, it will not. :)
> 
> As for GShade overwriting ReShade -- I'm confused. Is the installer owned by root, or did you successfully install GShade to the game, but you did so as root? The earlier part of your question indicates GShade wasn't successfully installed, so GShade shouldn't be showing up in your game at all.
> 
> If I'm misunderstanding, and you _did_ successfully install GShade to the game, but did so as root, you should be able to remove the install by using GShade with `sudo ./gshade_installer.sh`, although this should only be used for cleaning up. The installer should never be run as root.

I saved some files from my previous Windows installation of KCD (like mods etc) and put them in my new KCD Linux installation folder (including some Gshade files from the Windows installation) which I think is causing some issues.  Every time I delete the Gshade ini and dll files from my KCD folder, they are reinstalled as soon as I fire up the game.

I have just been trying to install Gshade again in the terminal and I seem to have half of the command right (the game location) but it keeps returning an error in relation to the wine prefix location "Not a valid WINEPREFIX, exiting".  Does the prefix part of the command have to be case-sensitive/identical to the wine prefix location and do I also have to include the folders which are part of the path but seem to be hidden?   If I look at the properties of the wine prefix folder then it shows extra folders/subfolders which aren't present in the navigation bar.  For example:

WINEPREFIX="$Home/joebloggs/.local/share/Steam/steamapps/compatdata/379430/pfx"

Does the word home have to be capitalised?  The way I have written it is how it appears and should I replace the $ symbol with a / symbol?

Also, the directories joebloggs/.local/share seem to be hidden directories.  Should they be included in the command?

Sorry if I sound like I don't know much about this............ it's because I don't.

**Comment by HereInPlainSight** [comment]
>Sorry if I sound like I don't know much about this............ it's because I don't.

Nothing to apologize for, we'll get you there.  :)

So, the short version is that you have a file system that starts with `/`.  This is the 'root' directory.  You have a user named `joebloggs`.  joeblogg's 'home' directory is `/home/joebloggs/`.  `$HOME` in this user's instance will mean `/home/joebloggs/`.  And, yes, you are correct that the variable name (and nearly everything else in Linux) is case sensitive, and for most purposes any variables (things that start with $) that you'll ever care about will be in all caps.

Long-than-intended-but-hopefully-informative story short: `WINEPREFIX="$HOME/.local/share/Steam/steamapps/compatdata/379430/pfx"` _or_ `WINEPREFIX="/home/joebloggs/.local/share/Steam/steamapps/compatdata/379430/pfx"` will be valid.

>Every time I delete the Gshade ini and dll files from my KCD folder, they are reinstalled as soon as I fire up the game.

This could be a problem but I wouldn't know the first thing about the how / why of it happening.  I assume it's a mod force-reinstalling it, perhaps?  I don't know anything about the game / mods available for it.

Now, as for the question of if you should include hidden folders -- yes.  Hidden files / folders are hidden for reasons, of course, but when it comes to a location, we need it to be exact, and if it's hidden, we still need to know _exactly_ where to go to find what we're looking for.  :)

**Comment by HereInPlainSight** [comment]
30 days since last comment -- closing.  Please re-open if there's any further issues!
